# This workflow deploys Databricks Asset Bundles using GitHub Actions

name: Databricks CI/CD Pipeline

on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    name: Deploy Databricks Bundle
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Databricks CLI v2
      - name: Set up Databricks CLI v2
        uses: databricks/setup-cli@main

      # Step 3: Validate the Databricks Asset Bundle
      - name: Validate Databricks bundle
        run: databricks bundle validate

      # Step 4: Deploy the bundle to the dev environment
      - name: Deploy to dev environment
        run: databricks bundle deploy --target dev --force-lock

      # Step 5: Run smoke test notebook
      # - name: Run smoke test
      #   run: databricks bundle run smoke_test --target dev
